// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Kilo Code
// Based on C# models from LoanTrackerJLC

import 'dart:typed_data';

class Response {
  int? code;
  String? message;

  Response({this.code, this.message});

  factory Response.fromJson(Map<String, dynamic> json) {
    return Response(
      code: json['Code'] as int?,
      message: json['Message'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'Code': code,
      'Message': message,
    };
  }
}

class UserMdl {
  String? password;
  int? userId;
  String? userName;
  int? userType;
  String? pin;
  String? fullName;
  String? address;

  UserMdl({
    this.password,
    this.userId,
    this.userName,
    this.userType,
    this.pin,
    this.fullName,
    this.address,

  });

  factory UserMdl.fromJson(Map<String, dynamic> json) {
    return UserMdl(
      password: json['password'] as String?,
      userId: json['userId'] as int?,
      userName: json['userName'] as String?,
      userType: json['userType'] as int?,
      pin: json['pin']?.toString(),
      fullName: json['fullName'] as String?,
      address: json['address'] as String? ?? json['address1'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'Password': password,
      'UserId': userId,
      'UserName': userName,
      'UserType': userType,
      'PIN': pin,
      'FullName': fullName,
      'Address': address,
    };
  }
}

class UserTypeMdl {
  int? userTypeId;
  String? userType;

  UserTypeMdl({this.userTypeId, this.userType});

  factory UserTypeMdl.fromJson(Map<String, dynamic> json) {
    return UserTypeMdl(
      userTypeId: json['UserTypeId'] as int?,
      userType: json['UserType'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'UserTypeId': userTypeId,
      'UserType': userType,
    };
  }
}

class PaymentMdl {
  int? payID;
  int? trxnID;
  int? loanID;
  double? amount;
  DateTime? dueDate;

  PaymentMdl({
    this.payID,
    this.trxnID,
    this.loanID,
    this.amount,
    this.dueDate,
  });

  factory PaymentMdl.fromJson(Map<String, dynamic> json) {
    return PaymentMdl(
      payID: json['PayID'] as int?,
      trxnID: json['TrxnID'] as int?,
      loanID: json['LoanID'] as int?,
      amount: (json['Amount'] as num?)?.toDouble(),
      dueDate: json['DueDate'] == null
          ? null
          : DateTime.parse(json['DueDate'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'PayID': payID,
      'TrxnID': trxnID,
      'LoanID': loanID,
      'Amount': amount,
      'DueDate': dueDate?.toIso8601String(),
    };
  }
}



class AccountMdl {
  int? pId;
  int? userId; // Changed from String to int to match API
  int? loanId;
  String? lastname;
  String? firstname;
  String? address1;
  String? clientFullName;
  String? userName;
  double? amount;
  double? interest;
  double? total;
  int? loanTerm;
  int? loanTypeID; // Added to match API
  String? loanDescription;
  String? img;
  Uint8List? idPicture;
  String? status;

  AccountMdl({
    this.pId,
    this.userId,
    this.loanId,
    this.lastname,
    this.firstname,
    this.address1,
    this.clientFullName,
    this.userName,
    this.amount,
    this.interest,
    this.total,
    this.loanTerm,
    this.loanTypeID,
    this.loanDescription,
    this.img,
    this.idPicture,
    this.status,
  });

  factory AccountMdl.fromJson(Map<String, dynamic> json) {
    return AccountMdl(
      pId: json['PId'] as int?,
      userId: json['UserId'] as int? ?? json['userId'] as int?,
      loanId: json['LoanId'] as int? ?? json['loanId'] as int?,
      lastname: json['lastname'] as String?,
      firstname: json['firstname'] as String?,
      address1: json['address1'] as String?,
      clientFullName: json['ClientFullName'] as String? ?? json['clientFullName'] as String?,
      userName: json['UserName'] as String? ?? json['userName'] as String?,
      amount: (json['Amount'] as num?)?.toDouble() ?? (json['loanAmount'] as num?)?.toDouble(),
      interest: (json['Interest'] as num?)?.toDouble() ?? (json['interest'] as num?)?.toDouble(),
      total: (json['Total'] as num?)?.toDouble() ?? (json['total'] as num?)?.toDouble(),
      loanTerm: json['LoanTerm'] as int? ?? json['loanTerm'] as int?,
      loanTypeID: json['LoanTypeID'] as int? ?? json['loanTypeID'] as int?,
      loanDescription: json['LoanDescription'] as String?,
      img: json['img'] as String?,
      idPicture: json['IDPicture'] == null
          ? null
          : Uint8List.fromList(List<int>.from(json['IDPicture'] as List)),
      status: json['Status'] as String? ?? json['status'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'PId': pId,
      'UserId': userId,
      'LoanId': loanId,
      'lastname': lastname,
      'firstname': firstname,
      'address1': address1,
      'ClientFullName': clientFullName,
      'UserName': userName,
      'Amount': amount,
      'Interest': interest,
      'Total': total,
      'LoanTerm': loanTerm,
      'LoanTypeID': loanTypeID,
      'LoanDescription': loanDescription,
      'img': img,
      'IDPicture': idPicture?.toList(),
      'Status': status,
    };
  }
}

class LoanTrxnMdl {
  int? id;
  int? loanID; // Fixed parameter name
  String? loanDescription;
  double? principalDue;
  double? interestDue;
  double? penaltiesDue;
  double? serviceFeesDue;
  double? totalDue;
  DateTime? dueDate;
  String? img;
  String? remarks;
  bool? isPaid;
  String? lastname;
  String? firstname;
  double? calculatedPenaltyForDisplay;
  double? totalDueWithCalcPenaltyForDisplay;
  double? weeklyDue; // Added missing field
  int? penaltyMonthsApplied; // Added missing field
  DateTime? monthlyDueDate; // Added missing field

  LoanTrxnMdl({
    this.id,
    this.loanID, // Fixed parameter
    this.loanDescription,
    this.principalDue,
    this.interestDue,
    this.penaltiesDue,
    this.serviceFeesDue,
    this.totalDue,
    this.dueDate,
    this.img,
    this.remarks,
    this.isPaid,
    this.lastname,
    this.firstname,
    this.calculatedPenaltyForDisplay,
    this.totalDueWithCalcPenaltyForDisplay,
    this.weeklyDue,
    this.penaltyMonthsApplied,
    this.monthlyDueDate,
  });

  factory LoanTrxnMdl.fromJson(Map<String, dynamic> json) {
    return LoanTrxnMdl(
      id: json['Id'] as int? ?? json['id'] as int?,
      loanID: json['LoanID'] as int? ?? json['loanID'] as int?,
      loanDescription: json['LoanDescription'] as String?,
      principalDue: (json['PrincipalDue'] as num?)?.toDouble() ?? (json['principalDue'] as num?)?.toDouble(),
      interestDue: (json['InterestDue'] as num?)?.toDouble() ?? (json['interestDue'] as num?)?.toDouble(),
      penaltiesDue: (json['PenaltiesDue'] as num?)?.toDouble() ?? (json['penaltiesDue'] as num?)?.toDouble(),
      serviceFeesDue: (json['ServiceFeesDue'] as num?)?.toDouble() ?? (json['serviceFeesDue'] as num?)?.toDouble(),
      totalDue: (json['TotalDue'] as num?)?.toDouble() ?? (json['totalDue'] as num?)?.toDouble(),
      dueDate: json['DueDate'] == null && json['dueDate'] == null
          ? null
          : DateTime.tryParse((json['DueDate'] ?? json['dueDate']) as String),
      img: json['img'] as String?,
      remarks: json['Remarks'] as String? ?? json['remarks'] as String?,
      isPaid: json['isPaid'] as bool? ?? json['IsPaid'] as bool?,
      lastname: json['lastname'] as String?,
      firstname: json['firstname'] as String?,
      calculatedPenaltyForDisplay: (json['CalculatedPenaltyForDisplay'] as num?)?.toDouble(),
      totalDueWithCalcPenaltyForDisplay: (json['TotalDueWithCalcPenaltyForDisplay'] as num?)?.toDouble(),
      weeklyDue: (json['WeeklyDue'] as num?)?.toDouble() ?? (json['weeklyDue'] as num?)?.toDouble(),
      penaltyMonthsApplied: json['PenaltyMonthsApplied'] as int? ?? json['penaltyMonthsApplied'] as int?,
      monthlyDueDate: json['MonthlyDueDate'] == null && json['monthlyDueDate'] == null
          ? null
          : DateTime.tryParse((json['MonthlyDueDate'] ?? json['monthlyDueDate']) as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'Id': id,
      'LoanID': loanID,
      'LoanDescription': loanDescription,
      'PrincipalDue': principalDue,
      'InterestDue': interestDue,
      'PenaltiesDue': penaltiesDue,
      'ServiceFeesDue': serviceFeesDue,
      'TotalDue': totalDue,
      'DueDate': dueDate?.toIso8601String(),
      'img': img,
      'Remarks': remarks,
      'isPaid': isPaid,
      'lastname': lastname,
      'firstname': firstname,
      'CalculatedPenaltyForDisplay': calculatedPenaltyForDisplay,
      'TotalDueWithCalcPenaltyForDisplay': totalDueWithCalcPenaltyForDisplay,
      'WeeklyDue': weeklyDue,
      'PenaltyMonthsApplied': penaltyMonthsApplied,
      'MonthlyDueDate': monthlyDueDate?.toIso8601String(),
    };
  }
}

class TrxnHistory {
  int? id; // Added missing field
  int? loanID;
  int? trxnID;
  double? amount;
  String? remarks;
  String? pDate;
  double? newAmountOnFee;
  int? userID; // Added missing field

  TrxnHistory({
    this.id,
    this.loanID,
    this.trxnID,
    this.amount,
    this.remarks,
    this.pDate,
    this.newAmountOnFee,
    this.userID,
  });

  factory TrxnHistory.fromJson(Map<String, dynamic> json) {
    return TrxnHistory(
      id: json['Id'] as int? ?? json['id'] as int?,
      loanID: json['LoanID'] as int? ?? json['loanID'] as int?,
      trxnID: json['TrxnID'] as int? ?? json['trxnID'] as int?,
      amount: (json['Amount'] as num?)?.toDouble() ?? (json['amount'] as num?)?.toDouble(),
      remarks: json['Remarks'] as String? ?? json['remarks'] as String?,
      pDate: json['PDate'] as String? ?? json['pDate'] as String?,
      newAmountOnFee: (json['NewAmountOnFee'] as num?)?.toDouble() ?? (json['newAmountOnFee'] as num?)?.toDouble(),
      userID: json['UserID'] as int? ?? json['userID'] as int?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'Id': id,
      'LoanID': loanID,
      'TrxnID': trxnID,
      'Amount': amount,
      'Remarks': remarks,
      'PDate': pDate,
      'NewAmountOnFee': newAmountOnFee,
      'UserID': userID,
    };
  }
}

// New model for comprehensive loan data from enhanced API
class ComprehensiveLoanData {
  int? loanId;
  int? userId;
  String? clientFullName;
  String? userName;
  double? loanAmount;
  double? interest;
  double? total;
  int? loanTerm;
  String? status;
  double? outstandingBalance;
  double? totalPaid;
  LoanTrxnMdl? nextPaymentDue;
  List<LoanTrxnMdl>? overduePayments;
  List<LoanTrxnMdl>? loanTransactions;
  List<TrxnHistory>? paymentHistory;
  Map<String, dynamic>? latestTransaction;

  ComprehensiveLoanData({
    this.loanId,
    this.userId,
    this.clientFullName,
    this.userName,
    this.loanAmount,
    this.interest,
    this.total,
    this.loanTerm,
    this.status,
    this.outstandingBalance,
    this.totalPaid,
    this.nextPaymentDue,
    this.overduePayments,
    this.loanTransactions,
    this.paymentHistory,
    this.latestTransaction,
  });

  factory ComprehensiveLoanData.fromJson(Map<String, dynamic> json) {
    return ComprehensiveLoanData(
      loanId: json['loanId'] as int?,
      userId: json['userId'] as int?,
      clientFullName: json['clientFullName'] as String?,
      userName: json['userName'] as String?,
      loanAmount: (json['loanAmount'] as num?)?.toDouble(),
      interest: (json['interest'] as num?)?.toDouble(),
      total: (json['total'] as num?)?.toDouble(),
      loanTerm: json['loanTerm'] as int?,
      status: json['status'] as String?,
      outstandingBalance: (json['outstandingBalance'] as num?)?.toDouble(),
      totalPaid: (json['totalPaid'] as num?)?.toDouble(),
      nextPaymentDue: json['nextPaymentDue'] == null
          ? null
          : LoanTrxnMdl.fromJson(json['nextPaymentDue'] as Map<String, dynamic>),
      overduePayments: json['overduePayments'] == null
          ? null
          : List<LoanTrxnMdl>.from(
        (json['overduePayments'] as List<dynamic>).map(
              (x) => LoanTrxnMdl.fromJson(x as Map<String, dynamic>),
        ),
      ),
      loanTransactions: json['loanTransactions'] == null
          ? null
          : List<LoanTrxnMdl>.from(
        (json['loanTransactions'] as List<dynamic>).map(
              (x) => LoanTrxnMdl.fromJson(x as Map<String, dynamic>),
        ),
      ),
      paymentHistory: json['paymentHistory'] == null
          ? null
          : List<TrxnHistory>.from(
        (json['paymentHistory'] as List<dynamic>).map(
              (x) => TrxnHistory.fromJson(x as Map<String, dynamic>),
        ),
      ),
      latestTransaction: json['latestTransaction'] as Map<String, dynamic>?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'loanId': loanId,
      'userId': userId,
      'clientFullName': clientFullName,
      'userName': userName,
      'loanAmount': loanAmount,
      'interest': interest,
      'total': total,
      'loanTerm': loanTerm,
      'status': status,
      'outstandingBalance': outstandingBalance,
      'totalPaid': totalPaid,
      'nextPaymentDue': nextPaymentDue?.toJson(),
      'overduePayments': overduePayments?.map((x) => x.toJson()).toList(),
      'loanTransactions': loanTransactions?.map((x) => x.toJson()).toList(),
      'paymentHistory': paymentHistory?.map((x) => x.toJson()).toList(),
      'latestTransaction': latestTransaction,
    };
  }
}

// Rest of the existing models remain the same...

class SmsMsgMdl {
  int? id;
  String? message;

  SmsMsgMdl({this.id, this.message});

  factory SmsMsgMdl.fromJson(Map<String, dynamic> json) {
    return SmsMsgMdl(
      id: json['Id'] as int?,
      message: json['Message'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'Id': id,
      'Message': message,
    };
  }
}

class LoanTypeMdl {
  int? loanTypeId;
  String? loanDescription;
  double? interestRate;
  double? penaltiesRate;
  double? term;

  LoanTypeMdl({
    this.loanTypeId,
    this.loanDescription,
    this.interestRate,
    this.penaltiesRate,
    this.term,
  });

  factory LoanTypeMdl.fromJson(Map<String, dynamic> json) {
    return LoanTypeMdl(
      loanTypeId: json['LoanTypeId'] as int?,
      loanDescription: json['LoanDescription'] as String?,
      interestRate: (json['InterestRate'] as num?)?.toDouble(),
      penaltiesRate: (json['PenaltiesRate'] as num?)?.toDouble(),
      term: (json['Term'] as num?)?.toDouble(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'LoanTypeId': loanTypeId,
      'LoanDescription': loanDescription,
      'InterestRate': interestRate,
      'PenaltiesRate': penaltiesRate,
      'Term': term,
    };
  }
}

class LoanTermMdl {
  int? termId;
  String? termDescription;
  int? termCount;

  LoanTermMdl({this.termId, this.termDescription, this.termCount});

  factory LoanTermMdl.fromJson(Map<String, dynamic> json) {
    return LoanTermMdl(
      termId: json['TermId'] as int?,
      termDescription: json['TermDescription'] as String?,
      termCount: json['TermCount'] as int?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'TermId': termId,
      'TermDescription': termDescription,
      'TermCount': termCount,
    };
  }
}

class LoanSummary {
  int? ctr;
  String? loanDescription;
  String? loanStatus;
  String? month;
  String? totalDue;
  String? dueDate;
  double? interestDue;
  double? penaltiesDue;
  double? principalDue;
  String? lastname;
  String? firstname;
  String? address1;
  String? userName;
  String? mobileNo;

  LoanSummary({
    this.ctr,
    this.loanDescription,
    this.loanStatus,
    this.month,
    this.totalDue,
    this.dueDate,
    this.interestDue,
    this.penaltiesDue,
    this.principalDue,
    this.lastname,
    this.firstname,
    this.address1,
    this.userName,
    this.mobileNo,
  });

  factory LoanSummary.fromJson(Map<String, dynamic> json) {
    return LoanSummary(
      ctr: json['CTR'] as int?,
      loanDescription: json['LoanDescription'] as String?,
      loanStatus: json['LoanStatus'] as String?,
      month: json['Month'] as String?,
      totalDue: json['TotalDue'] as String?,
      dueDate: json['DueDate'] as String?,
      interestDue: (json['InterestDue'] as num?)?.toDouble(),
      penaltiesDue: (json['PenaltiesDue'] as num?)?.toDouble(),
      principalDue: (json['PrincipalDue'] as num?)?.toDouble(),
      lastname: json['lastname'] as String?,
      firstname: json['firstname'] as String?,
      address1: json['address1'] as String?,
      userName: json['UserName'] as String?,
      mobileNo: json['MobileNo'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'CTR': ctr,
      'LoanDescription': loanDescription,
      'LoanStatus': loanStatus,
      'Month': month,
      'TotalDue': totalDue,
      'DueDate': dueDate,
      'InterestDue': interestDue,
      'PenaltiesDue': penaltiesDue,
      'PrincipalDue': principalDue,
      'lastname': lastname,
      'firstname': firstname,
      'address1': address1,
      'UserName': userName,
      'MobileNo': mobileNo,
    };
  }
}

class SmsMdl {
  String? email;
  String? password;
  String? recipients;
  String? message;
  String? apiCode;
  String? senderId;

  SmsMdl({
    this.email,
    this.password,
    this.recipients,
    this.message,
    this.apiCode,
    this.senderId,
  });

  factory SmsMdl.fromJson(Map<String, dynamic> json) {
    return SmsMdl(
      email: json['Email'] as String?,
      password: json['Password'] as String?,
      recipients: json['Recipients'] as String?,
      message: json['Message'] as String?,
      apiCode: json['ApiCode'] as String?,
      senderId: json['SenderId'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'Email': email,
      'Password': password,
      'Recipients': recipients,
      'Message': message,
      'ApiCode': apiCode,
      'SenderId': senderId,
    };
  }
}

class MsgMdl {
  String? mobile;
  String? message;

  MsgMdl({this.mobile, this.message});

  factory MsgMdl.fromJson(Map<String, dynamic> json) {
    return MsgMdl(
      mobile: json['Mobile'] as String?,
      message: json['Message'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'Mobile': mobile,
      'Message': message,
    };
  }
}

class PrintValue {
  String? code;
  String? value;
  String? fileType;
  Uint8List? actualSize;
  String? description;
  DateTime? dateModified;

  PrintValue({
    this.code,
    this.value,
    this.fileType,
    this.actualSize,
    this.description,
    this.dateModified,
  });

  factory PrintValue.fromJson(Map<String, dynamic> json) {
    return PrintValue(
      code: json['Code'] as String?,
      value: json['Value'] as String?,
      fileType: json['FileType'] as String?,
      actualSize: json['ActualSize'] == null
          ? null
          : Uint8List.fromList(List<int>.from(json['ActualSize'] as List)),
      description: json['Description'] as String?,
      dateModified: json['DateModified'] == null
          ? null
          : DateTime.parse(json['DateModified'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'Code': code,
      'Value': value,
      'FileType': fileType,
      'ActualSize': actualSize?.toList(),
      'Description': description,
      'DateModified': dateModified?.toIso8601String(),
    };
  }
}

class AccountAssignment {
  int assignmentID;
  int loanId;
  int collectorUserID;
  int assignedByUserID;
  DateTime assignmentTimestamp;
  String status;
  String? notes;

  AccountAssignment({
    required this.assignmentID,
    required this.loanId,
    required this.collectorUserID,
    required this.assignedByUserID,
    required this.assignmentTimestamp,
    required this.status,
    this.notes,
  });

  factory AccountAssignment.fromJson(Map<String, dynamic> json) {
    return AccountAssignment(
      assignmentID: json['AssignmentID'] as int,
      loanId: json['LoanId'] as int,
      collectorUserID: json['CollectorUserID'] as int,
      assignedByUserID: json['AssignedByUserID'] as int,
      assignmentTimestamp:
      DateTime.parse(json['AssignmentTimestamp'] as String),
      status: json['Status'] as String,
      notes: json['Notes'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'AssignmentID': assignmentID,
      'LoanId': loanId,
      'CollectorUserID': collectorUserID,
      'AssignedByUserID': assignedByUserID,
      'AssignmentTimestamp': assignmentTimestamp.toIso8601String(),
      'Status': status,
      'Notes': notes,
    };
  }
}

class AccountAssignmentViewMdl {
  int assignmentID;
  int loanId;
  String? clientFullName;
  double? loanAmount;
  String? collectorFullName;
  String? assignedByFullName;
  DateTime assignmentTimestamp;
  String? status;
  String? notes;
  String? loanStatus;
  int? loanTypeID;
  List<LoanTrxnMdl>? repaymentSchedule;

  AccountAssignmentViewMdl({
    required this.assignmentID,
    required this.loanId,
    this.clientFullName,
    this.loanAmount,
    this.collectorFullName,
    this.assignedByFullName,
    required this.assignmentTimestamp,
    this.status,
    this.notes,
    this.loanStatus,
    this.loanTypeID,
    this.repaymentSchedule,
  });

  factory AccountAssignmentViewMdl.fromJson(Map<String, dynamic> json) {
    return AccountAssignmentViewMdl(
      assignmentID: json['AssignmentID'] as int,
      loanId: json['LoanId'] as int,
      clientFullName: json['ClientFullName'] as String?,
      loanAmount: (json['LoanAmount'] as num?)?.toDouble(),
      collectorFullName: json['CollectorFullName'] as String?,
      assignedByFullName: json['AssignedByFullName'] as String?,
      assignmentTimestamp:
      DateTime.parse(json['AssignmentTimestamp'] as String),
      status: json['Status'] as String?,
      notes: json['Notes'] as String?,
      loanStatus: json['LoanStatus'] as String?,
      loanTypeID: json['LoanTypeID'] as int?,
      repaymentSchedule: json['RepaymentSchedule'] == null
          ? null
          : List<LoanTrxnMdl>.from(
        (json['RepaymentSchedule'] as List<dynamic>).map(
              (x) => LoanTrxnMdl.fromJson(x as Map<String, dynamic>),
        ),
      ),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'AssignmentID': assignmentID,
      'LoanId': loanId,
      'ClientFullName': clientFullName,
      'LoanAmount': loanAmount,
      'CollectorFullName': collectorFullName,
      'AssignedByFullName': assignedByFullName,
      'AssignmentTimestamp': assignmentTimestamp.toIso8601String(),
      'Status': status,
      'Notes': notes,
      'LoanStatus': loanStatus,
      'LoanTypeID': loanTypeID,
      'RepaymentSchedule': repaymentSchedule?.map((x) => x.toJson()).toList(),
    };
  }
}

class LoanMdl {
  int? loanId;
  int? userId;
  int? loanTypeID;
  double? amount;
  double? interest;
  double? total;
  int? loanTerm;
  String? status;

  LoanMdl({
    this.loanId,
    this.userId,
    this.loanTypeID,
    this.amount,
    this.interest,
    this.total,
    this.loanTerm,
    this.status,
  });

  factory LoanMdl.fromJson(Map<String, dynamic> json) {
    return LoanMdl(
      loanId: json['loanId'] as int?,
      userId: json['userId'] as int?,
      loanTypeID: json['loanTypeID'] as int?,
      amount: (json['amount'] as num?)?.toDouble(),
      interest: (json['interest'] as num?)?.toDouble(),
      total: (json['total'] as num?)?.toDouble(),
      loanTerm: json['loanTerm'] as int?,
      status: json['status'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'loanId': loanId,
      'userId': userId,
      'loanTypeID': loanTypeID,
      'amount': amount,
      'interest': interest,
      'total': total,
      'loanTerm': loanTerm,
      'status': status,
    };
  }
}

class AssignedLoanMdl {
  LoanMdl? loan;
  UserMdl? client;

  AssignedLoanMdl({this.loan, this.client});

  factory AssignedLoanMdl.fromJson(Map<String, dynamic> json) {
    return AssignedLoanMdl(
      loan: json['loan'] == null
          ? null
          : LoanMdl.fromJson(json['loan'] as Map<String, dynamic>),
      client: json['client'] == null
          ? null
          : UserMdl.fromJson(json['client'] as Map<String, dynamic>),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'loan': loan?.toJson(),
      'client': client?.toJson(),
    };
  }
}